"""Damage engine tests.

The core verification is roll parity with reference fixtures generated by
@smogon/calc (the engine behind the NCP Champions calculator), using identical
stat/type/move inputs from our own pokedex — so any failure is a mechanics bug,
not a data difference. Champions uses the standard 16 damage rolls (85..100),
so fixtures store the full 16-roll reference array and the test compares against
it directly.
"""

import json
from pathlib import Path

import pytest

from vgc_toolkit.core import damage
from vgc_toolkit.core.damage import Combatant, Field, calculate, describe
from vgc_toolkit.core.stats import SPSpread

FIXTURES = json.loads(
    (Path(__file__).parent / "fixtures_damage.json").read_text())


def _combatant(pokemon_id: str, opts: dict) -> Combatant:
    status_map = {"brn": "burn", "par": "paralysis", "": None}
    return Combatant(
        pokemon_id=pokemon_id,
        spread=SPSpread.from_dict(opts.get("sp", {})),
        alignment=opts.get("nature", "Serious"),
        ability=opts.get("ability", "Pressure"),  # fixtures' neutral default
        item=opts.get("item"),
        stages=opts.get("boosts", {}),
        status=status_map.get(opts.get("status", ""), opts.get("status")),
    )


def _field(case: dict) -> Field:
    f, m = case.get("field", {}), case.get("move_opts", {})
    return Field(
        weather=(f.get("weather") or "none").lower(),
        terrain=(f.get("terrain") or "none").lower(),
        is_spread=True if m.get("spread") else None,
        is_crit=bool(m.get("crit")),
        reflect=bool(f.get("reflect")),
        light_screen=bool(f.get("lightScreen")),
        friend_guard=bool(f.get("friendGuard")),
        helping_hand=bool(f.get("helpingHand")),
    )


class TestReferenceParity:
    @pytest.mark.parametrize("case", FIXTURES, ids=[c["label"] for c in FIXTURES])
    def test_rolls_match_reference(self, case):
        result = calculate(
            _combatant(case["attacker"], case["attacker_opts"]),
            _combatant(case["defender"], case["defender_opts"]),
            case["move"],
            _field(case),
        )
        # Champions uses the standard 16 rolls (85..100); fixtures store the
        # full 16-roll reference array, so compare against it directly.
        expected = case["expected_rolls"]
        assert result["rolls"] == expected, (
            f"{case['label']}: {result['rolls']} != {expected}")


class TestEngineBehavior:
    def test_immunity_by_type(self):
        r = calculate(Combatant("golurk-mega", ability="Iron Fist"),
                      Combatant("dragonite-mega", ability="Multiscale"),
                      "Earthquake")
        assert r["rolls"] == [0] * 16
        assert any("immune" in n for n in r["notes"])

    def test_immunity_by_ability(self):
        r = calculate(Combatant("primarina", ability="Torrent"),
                      Combatant("politoed", ability="Water Absorb"), "Surf")
        assert r["rolls"] == [0] * 16

    def test_status_moves_deal_zero(self):
        r = calculate(Combatant("clefable"), Combatant("kingambit"), "Thunder Wave")
        assert r["rolls"] == [0] * 16

    def test_mega_sol_no_longer_flagged_unknown(self):
        r = calculate(Combatant("meganium-mega", ability="Mega Sol",
                                spread=SPSpread(spa=32)),
                      Combatant("kingambit"), "Moonblast")
        assert not any("unknown" in n.lower() for n in r["notes"])

    def test_variable_bp_flagged_and_overridable(self):
        base = calculate(Combatant("kingambit"), Combatant("clefable"), "Gyro Ball")
        assert any("variable base power" in n for n in base["notes"])
        overridden = calculate(Combatant("kingambit"), Combatant("clefable"),
                               "Gyro Ball", bp_override=120)
        assert max(overridden["rolls"]) > max(base["rolls"])

    def test_weight_based_moves_use_pokedex_weights(self):
        def bp(att, dfn, move, atk_ability=None, def_ability=None):
            return calculate(Combatant(att, ability=atk_ability),
                             Combatant(dfn, ability=def_ability), move)["base_power"]
        # Low Kick / Grass Knot: the target's weight (Pikachu 6 kg, Clefable 40 kg, Snorlax 460 kg).
        assert bp("kingambit", "pikachu", "Low Kick") == 20
        assert bp("kingambit", "clefable", "Low Kick") == 60
        assert bp("kingambit", "snorlax", "Low Kick") == 120
        assert bp("venusaur", "snorlax", "Grass Knot") == 120
        r = calculate(Combatant("kingambit"), Combatant("snorlax"), "Low Kick")
        assert any("120 BP" in n and "460" in n for n in r["notes"])
        assert not any("variable base power" in n for n in r["notes"])
        assert calculate(Combatant("kingambit"), Combatant("snorlax"), "Low Kick",
                         bp_override=40)["base_power"] == 40
        # Heavy Slam / Heat Crash: user weight over target weight (460 / 6 -> 120; equal -> 40).
        assert bp("snorlax", "pikachu", "Heavy Slam") == 120
        assert bp("snorlax", "snorlax", "Heavy Slam") == 40
        # Light Metal halves the holder: Metagross 550 kg -> 275 kg over Kingambit's 120 kg (4.6 -> 100, 2.3 -> 60).
        assert bp("metagross", "kingambit", "Heavy Slam", atk_ability="Clear Body") == 100
        assert bp("metagross", "kingambit", "Heavy Slam", atk_ability="Light Metal") == 60
        # ... and as a target: Grass Knot into a Light Metal Scizor (118 -> 59 kg) drops from 100 to 80.
        assert bp("venusaur", "scizor", "Grass Knot", def_ability="Technician") == 100
        assert bp("venusaur", "scizor", "Grass Knot", def_ability="Light Metal") == 80
        # Heavy Metal doubles: Aggron 360 kg over Kingambit 120 kg is 3.0 -> 80, 720 kg is 6.0 -> 120.
        assert bp("aggron", "kingambit", "Heavy Slam", atk_ability="Sturdy") == 80
        assert bp("aggron", "kingambit", "Heavy Slam", atk_ability="Heavy Metal") == 120

    def test_ko_chance_sanity(self):
        # A hit dealing 50-60% must be a guaranteed 2HKO and 0% OHKO.
        rolls = [110 + i for i in range(16)]  # vs 200 HP
        ko = damage._ko_chance(rolls, 200)
        assert "1hko" not in ko or ko["1hko"] == 0
        assert ko["2hko"] == 100.0

    def test_guaranteed_ohko_reads_100(self):
        # Regression: a hit lethal on every roll must report a guaranteed OHKO
        # (100.0) through the real engine — not 93.8% — and must not emit
        # phantom follow-up KO rows. Previously masked by a 15-roll-over-/16 bug.
        a = Combatant("kingambit", spread=SPSpread(atk=32), alignment="Adamant")
        d = Combatant("clefable", current_hp_fraction=0.1)  # chipped: every roll kills
        r = calculate(a, d, "Iron Head")
        assert min(r["rolls"]) > r["defender_current_hp"]   # confirm every roll lethal
        assert r["ko_chances"]["1hko"] == 100.0
        assert "2hko" not in r["ko_chances"]                # early-exit fired

    def test_describe_format(self):
        a = Combatant("chandelure-mega", spread=SPSpread(spa=32),
                      alignment="Modest")
        d = Combatant("kingambit", spread=SPSpread(hp=32))
        r = calculate(a, d, "Heat Wave")
        s = describe(a, d, r)
        assert "Mega Chandelure" in s and "Heat Wave" in s and "%" in s


class TestChampionsAbilities:
    def test_dragonize_converts_and_boosts(self):
        plain = calculate(Combatant("feraligatr-mega", ability="Torrent",
                                    spread=SPSpread(atk=32), alignment="Adamant"),
                          Combatant("dragapult"), "Double-Edge")
        drag = calculate(Combatant("feraligatr-mega", ability="Dragonize",
                                   spread=SPSpread(atk=32), alignment="Adamant"),
                         Combatant("dragapult"), "Double-Edge")
        # Normal -> Dragon: gains 2x vs Dragapult, x1.2 power, and Dragon STAB
        assert drag["type_effectiveness"] == 2.0
        assert plain["type_effectiveness"] == 1.0
        assert min(drag["rolls"]) > min(plain["rolls"]) * 2

    def test_mega_sol_sun_boost_without_weather(self):
        # Fire move from a Mega Sol user is x1.5 with no weather set
        plain_fire = calculate(Combatant("clefable", spread=SPSpread(spa=32)),
                               Combatant("kingambit"), "Mystical Fire")
        sol_fire = calculate(Combatant("clefable", ability="Mega Sol",
                                       spread=SPSpread(spa=32)),
                             Combatant("kingambit"), "Mystical Fire")
        assert min(sol_fire["rolls"]) > min(plain_fire["rolls"]) * 1.4

    def test_piercing_drill_through_protect(self):
        blocked = calculate(Combatant("excadrill-mega", ability="Sand Force",
                                      spread=SPSpread(atk=32)),
                            Combatant("kingambit"), "Iron Head",
                            Field(defender_protected=True))
        pierced = calculate(Combatant("excadrill-mega", ability="Piercing Drill",
                                      spread=SPSpread(atk=32)),
                            Combatant("kingambit"), "Iron Head",
                            Field(defender_protected=True))
        full = calculate(Combatant("excadrill-mega", ability="Piercing Drill",
                                   spread=SPSpread(atk=32)),
                         Combatant("kingambit"), "Iron Head")
        assert blocked["rolls"] == [0] * 16
        import math
        assert 0 < max(pierced["rolls"]) <= math.ceil(max(full["rolls"]) * 0.27)

    def test_spicy_spray_notes_burn(self):
        r = calculate(Combatant("kingambit", spread=SPSpread(atk=32)),
                      Combatant("scovillain-mega", ability="Spicy Spray"),
                      "Kowtow Cleave")
        assert any("Spicy Spray" in n for n in r["notes"])
        assert max(r["rolls"]) > 0



class TestFieldMechanics:
    def test_fairy_aura(self):
        plain = calculate(Combatant("clefable", spread=SPSpread(spa=32)),
                          Combatant("kingambit"), "Moonblast")
        aura = calculate(Combatant("clefable", spread=SPSpread(spa=32)),
                         Combatant("kingambit"), "Moonblast",
                         Field(fairy_aura=True))
        ratio = min(aura["rolls"]) / min(plain["rolls"])
        assert 1.28 < ratio < 1.38

    def test_gravity_grounds_flying_and_levitate(self):
        atk = Combatant("golurk-mega", spread=SPSpread(atk=32), ability="Iron Fist")
        flying = Combatant("skarmory-mega")
        r = calculate(atk, flying, "Earthquake", Field(gravity=True))
        assert max(r["rolls"]) > 0
        assert r["type_effectiveness"] == 2.0  # Steel 2x, Flying grounded by gravity
        lev = Combatant("chandelure-mega", ability="Levitate")
        r2 = calculate(atk, lev, "Earthquake", Field(gravity=True))
        assert max(r2["rolls"]) > 0

    def test_singles_screens_halve(self):
        atk = Combatant("kingambit", spread=SPSpread(atk=32))
        dfn = Combatant("clefable", spread=SPSpread(hp=32))
        dbl = calculate(atk, dfn, "Iron Head", Field(reflect=True))
        sgl = calculate(atk, dfn, "Iron Head",
                        Field(reflect=True, is_doubles=False))
        assert min(sgl["rolls"]) < min(dbl["rolls"])


class TestWeatherBall:
    def test_sun_weather_ball_is_boosted_fire(self):
        zard = Combatant("chandelure-mega", spread=SPSpread(spa=32),
                         alignment="Modest")
        kingambit = Combatant("kingambit", spread=SPSpread(hp=32))
        plain = calculate(zard, kingambit, "Weather Ball")
        sunny = calculate(zard, kingambit, "Weather Ball", Field(weather="sun"))
        # Fire-type in sun: 2x eff vs Steel, 100 BP, x1.5 sun, STAB
        assert sunny["type_effectiveness"] == 2.0
        assert plain["type_effectiveness"] == 0.5  # Normal resisted by Steel
        assert min(sunny["rolls"]) > min(plain["rolls"]) * 4
        assert any("Weather Ball" in n for n in sunny["notes"])

    def test_rain_weather_ball_is_water(self):
        r = calculate(Combatant("politoed", spread=SPSpread(spa=32)),
                      Combatant("torkoal"), "Weather Ball",
                      Field(weather="rain"))
        assert r["type_effectiveness"] == 2.0  # Water vs Fire

    def test_mega_sol_makes_weather_ball_fire(self):
        r = calculate(Combatant("meganium-mega", ability="Mega Sol",
                                spread=SPSpread(spa=32)),
                      Combatant("kingambit"), "Weather Ball")
        assert r["type_effectiveness"] == 2.0


class TestGrassyTerrainGroundHalving:
    """Grassy Terrain halves Earthquake / Bulldoze / Magnitude against grounded
    targets (Gen 9 rule). Only the three quake moves, only grounded defenders."""

    def _calc(self, move, defender_id, terrain, ability=None):
        from vgc_toolkit.core.damage import Combatant, Field, calculate
        from vgc_toolkit.core.stats import SPSpread
        atk = Combatant("garchomp", spread=SPSpread(atk=32), alignment="Adamant",
                        ability="Rough Skin")
        dfn = Combatant(defender_id, spread=SPSpread(hp=32), ability=ability)
        return calculate(atk, dfn, move, Field(terrain=terrain))["rolls"]

    def test_earthquake_halved_into_grounded_target(self):
        plain = self._calc("Earthquake", "golisopod-mega", "none")
        grassy = self._calc("Earthquake", "golisopod-mega", "grassy")
        assert max(grassy) < max(plain)
        assert 0.45 <= max(grassy) / max(plain) <= 0.55

    def test_bulldoze_halved_but_other_ground_moves_are_not(self):
        assert max(self._calc("Bulldoze", "golisopod-mega", "grassy")) < \
            max(self._calc("Bulldoze", "golisopod-mega", "none"))
        # High Horsepower / Stomping Tantrum keep full power on Grassy Terrain
        assert self._calc("High Horsepower", "golisopod-mega", "grassy") == \
            self._calc("High Horsepower", "golisopod-mega", "none")

    def test_airborne_defender_is_not_halved(self):
        # Levitate/Flying targets are not grounded (and are Ground-immune anyway);
        # a non-immune airborne check needs Gravity, so assert on a grounded
        # Steel type vs the same target under Levitate via the grounded flag.
        from vgc_toolkit.core.damage import Combatant, Field, calculate
        from vgc_toolkit.core.stats import SPSpread
        atk = Combatant("garchomp", spread=SPSpread(atk=32), alignment="Adamant",
                        ability="Rough Skin")
        dfn = Combatant("kingambit", spread=SPSpread(hp=32))
        plain = calculate(atk, dfn, "Earthquake", Field(terrain="none"))["rolls"]
        grassy = calculate(atk, dfn, "Earthquake", Field(terrain="grassy"))["rolls"]
        assert max(grassy) < max(plain)   # grounded Kingambit: halved
        # Grassy also does not touch non-Ground moves
        assert calculate(atk, dfn, "Dragon Claw", Field(terrain="grassy"))["rolls"] == \
            calculate(atk, dfn, "Dragon Claw", Field(terrain="none"))["rolls"]


class TestHeldItems:
    """Damage-relevant held items are data-driven from items.json mechanics tags
    (Life Orb, Expert Belt, Muscle Band, Wise Glasses, Metronome, Focus Sash,
    Iron Ball) and applied at the reference implementation's formula points."""

    def _rolls(self, move, item=None, defender_id="incineroar", **kw):
        atk = Combatant("garchomp", spread=SPSpread(atk=32, spa=32), alignment="Serious",
                        ability="Pressure", item=item, **kw)
        dfn = Combatant(defender_id, spread=SPSpread(hp=32), ability="Pressure")
        return calculate(atk, dfn, move)

    def test_life_orb_is_a_final_x1_3_with_recoil_note(self):
        plain = self._rolls("Earthquake")["rolls"]
        orb = self._rolls("Earthquake", item="Life Orb")
        assert orb["rolls"] == [max(1, damage.poke_round(r * 5324 / 4096)) for r in plain]
        assert max(orb["rolls"]) > max(plain)
        assert any("Life Orb" in n and "10%" in n for n in orb["notes"])

    def test_expert_belt_only_boosts_super_effective_hits(self):
        se_plain = self._rolls("Earthquake")["rolls"]              # Ground into Fire/Dark: 2x
        se_belt = self._rolls("Earthquake", item="Expert Belt")["rolls"]
        assert se_belt == [max(1, damage.poke_round(r * 4915 / 4096)) for r in se_plain]
        assert self._rolls("Dragon Claw", item="Expert Belt")["rolls"] == \
            self._rolls("Dragon Claw")["rolls"]                  # neutral: no boost

    def test_muscle_band_and_wise_glasses_are_category_specific(self):
        phys, spec = "Dragon Claw", "Draco Meteor"
        band = max(self._rolls(phys, item="Muscle Band")["rolls"])
        assert 1.05 <= band / max(self._rolls(phys)["rolls"]) <= 1.15
        assert self._rolls(spec, item="Muscle Band")["rolls"] == self._rolls(spec)["rolls"]
        glasses = max(self._rolls(spec, item="Wise Glasses")["rolls"])
        assert 1.05 <= glasses / max(self._rolls(spec)["rolls"]) <= 1.15
        assert self._rolls(phys, item="Wise Glasses")["rolls"] == self._rolls(phys)["rolls"]

    def test_metronome_scales_with_streak_and_caps_at_x2(self):
        base = max(self._rolls("Dragon Claw")["rolls"])
        fresh = self._rolls("Dragon Claw", item="Metronome")
        assert max(fresh["rolls"]) == base                        # first use: no boost
        assert any("Metronome" in n and "move_streak" in n for n in fresh["notes"])
        one = max(self._rolls("Dragon Claw", item="Metronome", move_streak=1)["rolls"])
        five = max(self._rolls("Dragon Claw", item="Metronome", move_streak=5)["rolls"])
        nine = max(self._rolls("Dragon Claw", item="Metronome", move_streak=9)["rolls"])
        assert 1.15 <= one / base <= 1.25
        assert 1.9 <= five / base <= 2.05
        assert nine == five                                       # capped

    def test_focus_sash_blocks_the_ohko_only_from_full_hp_and_single_hits(self):
        atk = Combatant("baxcalibur", spread=SPSpread(atk=32), alignment="Adamant",
                        ability="Pressure")
        sash = calculate(atk, Combatant("garchomp", item="Focus Sash"), "Icicle Crash")
        assert sash["ko_chances"]["1hko"] == 0.0
        assert sash["ko_chances"]["2hko"] == 100.0
        assert any("Focus Sash" in n for n in sash["notes"])
        assert calculate(atk, Combatant("garchomp"), "Icicle Crash")["ko_chances"]["1hko"] == 100.0
        chipped = Combatant("garchomp", item="Focus Sash", current_hp_fraction=0.9)
        assert calculate(atk, chipped, "Icicle Crash")["ko_chances"]["1hko"] == 100.0
        multi = calculate(atk, Combatant("garchomp", item="Focus Sash"), "Icicle Spear", hits=5)
        assert multi["ko_chances"]["1hko"] == 100.0               # later hits break the sash

    def test_iron_ball_grounds_a_flying_defender(self):
        atk = Combatant("garchomp", spread=SPSpread(atk=32), alignment="Adamant",
                        ability="Pressure")
        assert calculate(atk, Combatant("pelipper", spread=SPSpread(hp=32)), "Earthquake")["rolls"] == [0] * 16
        grounded = Combatant("pelipper", spread=SPSpread(hp=32), item="Iron Ball")
        assert max(calculate(atk, grounded, "Earthquake")["rolls"]) > 0

    def test_items_without_damage_mechanics_change_nothing(self):
        for item in ("Leftovers", "Sitrus Berry", "Choice Scarf", "Wide Lens", "Golisopodite"):
            assert self._rolls("Earthquake", item=item)["rolls"] == self._rolls("Earthquake")["rolls"], item


class TestAteAbilities:
    """Aerilate / Pixilate / Refrigerate (and Champions' Dragonize) turn the
    user's Normal-type moves into the ability's type at x1.2, with STAB judged
    on the new type; the result reports the effective type."""

    def _calc(self, attacker_id, ability, move, defender_id, field=None):
        atk = Combatant(attacker_id, spread=SPSpread(atk=32, spa=32), ability=ability)
        dfn = Combatant(defender_id, spread=SPSpread(hp=32), ability="Pressure")
        return calculate(atk, dfn, move, field)

    def test_pixilate_hyper_voice_is_stab_fairy(self):
        plain = self._calc("sylveon", "Pressure", "Hyper Voice", "garchomp")
        pix = self._calc("sylveon", "Pixilate", "Hyper Voice", "garchomp")
        assert plain["type"] == "Normal" and pix["type"] == "Fairy"
        assert pix["type_effectiveness"] == 2.0            # Fairy into Dragon/Ground
        ratio = max(pix["rolls"]) / max(plain["rolls"])    # x1.2 power, x1.5 STAB, x2 type
        assert 3.4 <= ratio <= 3.8
        assert any("Pixilate" in n for n in pix["notes"])

    def test_aerilate_mega_salamence_double_edge(self):
        plain = self._calc("salamence-mega", "Pressure", "Double-Edge", "kingambit")
        aer = self._calc("salamence-mega", "Aerilate", "Double-Edge", "kingambit")
        assert aer["type"] == "Flying"
        ratio = max(aer["rolls"]) / max(plain["rolls"])    # both resisted by Steel: x1.2, x1.5 STAB
        assert 1.7 <= ratio <= 1.9
        # non-Normal moves are untouched
        assert self._calc("salamence-mega", "Aerilate", "Dragon Claw", "kingambit")["rolls"] == \
            self._calc("salamence-mega", "Pressure", "Dragon Claw", "kingambit")["rolls"]

    def test_refrigerate_and_dragonize_share_the_mechanic(self):
        ice = self._calc("aurorus", "Refrigerate", "Hyper Voice", "garchomp")
        assert ice["type"] == "Ice" and ice["type_effectiveness"] == 4.0
        drg = self._calc("feraligatr-mega", "Dragonize", "Hyper Voice", "garchomp")
        assert drg["type"] == "Dragon"

    def test_weather_ball_keeps_its_weather_type(self):
        clear = self._calc("sylveon", "Pixilate", "Weather Ball", "garchomp")
        assert clear["type"] == "Fairy"                     # Normal in clear weather: converted
        sun = self._calc("sylveon", "Pixilate", "Weather Ball", "garchomp", Field(weather="sun"))
        assert sun["type"] == "Fire"                        # weather typing wins


class TestConfirmedMCMegaAbilities:
    """Abilities Champions confirmed for the Regulation M-C megas (2026-09-03):
    Aura Guard (new: halves damage taken from contact moves), Levitate,
    Sharpness, Aerilate. The data's default ability is used where none is given."""

    def test_aura_guard_halves_contact_moves_only(self):
        atk = Combatant("kingambit", spread=SPSpread(atk=32, spa=32), alignment="Serious",
                        ability="Pressure")
        plain_z = Combatant("lucario-mega-z", spread=SPSpread(hp=32), ability="Pressure")
        guard_z = Combatant("lucario-mega-z", spread=SPSpread(hp=32), ability="Aura Guard")
        plain = calculate(atk, plain_z, "Kowtow Cleave")["rolls"]
        guarded = calculate(atk, guard_z, "Kowtow Cleave")
        assert guarded["rolls"] == [max(1, damage.poke_round(r * 2048 / 4096)) for r in plain]
        assert any("Aura Guard" in n for n in guarded["notes"])
        # non-contact damage is untouched
        assert calculate(atk, guard_z, "Dark Pulse")["rolls"] == \
            calculate(atk, plain_z, "Dark Pulse")["rolls"]

    def test_mega_garchomp_z_levitate_is_ground_immune_by_default(self):
        atk = Combatant("garchomp", spread=SPSpread(atk=32), alignment="Adamant", ability="Rough Skin")
        r = calculate(atk, Combatant("garchomp-mega-z", spread=SPSpread(hp=32)), "Earthquake")
        assert r["rolls"] == [0] * 16 and any("Levitate" in n for n in r["notes"])

    def test_mega_absol_z_sharpness_boosts_slicing_moves_by_default(self):
        sharp = Combatant("absol-mega-z", spread=SPSpread(atk=32), alignment="Adamant")
        plain = Combatant("absol-mega-z", spread=SPSpread(atk=32), alignment="Adamant", ability="Pressure")
        dfn = Combatant("incineroar", spread=SPSpread(hp=32), ability="Pressure")
        ratio = max(calculate(sharp, dfn, "Night Slash")["rolls"]) / \
            max(calculate(plain, dfn, "Night Slash")["rolls"])
        assert 1.45 <= ratio <= 1.55
        assert calculate(sharp, dfn, "Shadow Claw")["rolls"] == \
            calculate(plain, dfn, "Shadow Claw")["rolls"]        # not a slicing move

    def test_mega_salamence_aerilate_by_default(self):
        mence = Combatant("salamence-mega", spread=SPSpread(atk=32), alignment="Adamant")
        dfn = Combatant("incineroar", spread=SPSpread(hp=32), ability="Pressure")
        assert calculate(mence, dfn, "Double-Edge")["type"] == "Flying"


class TestWaterBubble:
    """Water Bubble is an attack-stat modifier both ways (x2 for the holder's
    Water moves, x0.5 for Fire moves aimed at it) and a burn immunity. The
    expected rolls are the distinct one-hit damages the pokemon-showdown
    champions engine produced across 48 fixed seeds (no crits)."""

    ARAQ_ATK = Combatant("araquanid", spread=SPSpread(atk=32), alignment="Adamant",
                         ability="Water Bubble", item="Sitrus Berry")
    ARAQ_DEF = Combatant("araquanid", spread=SPSpread(hp=32), alignment="Adamant",
                         ability="Water Bubble", item="Sitrus Berry")
    KING = Combatant("kingambit", spread=SPSpread(hp=32), alignment="Adamant",
                     ability="Defiant", item="Leftovers")
    INCIN = Combatant("incineroar", spread=SPSpread(atk=32), alignment="Adamant",
                      ability="Blaze", item="Leftovers")
    SINGLES = Field(is_doubles=False)

    def test_water_moves_are_doubled_to_the_engine_rolls(self):
        r = calculate(self.ARAQ_ATK, self.KING, "Liquidation", self.SINGLES)
        assert {93, 94, 96, 97, 99, 100, 102, 103, 105, 106, 108, 109} <= set(r["rolls"])
        assert any("Water Bubble" in n for n in r["notes"])
        plain = Combatant("araquanid", spread=SPSpread(atk=32), alignment="Adamant",
                          ability="Water Absorb", item="Sitrus Berry")
        base = calculate(plain, self.KING, "Liquidation", self.SINGLES)["rolls"]
        assert all(1.9 < a / b < 2.1 for a, b in zip(r["rolls"], base))

    def test_other_types_are_untouched(self):
        r = calculate(self.ARAQ_ATK, self.KING, "Lunge", self.SINGLES)
        assert {43, 45, 46, 48, 49, 51, 52} <= set(r["rolls"])
        assert not any("Water Bubble" in n for n in r["notes"])

    def test_fire_into_the_holder_is_halved_on_the_attack_stat(self):
        r = calculate(self.INCIN, self.ARAQ_DEF, "Flare Blitz", self.SINGLES)
        assert {55, 57, 58, 60, 61, 63, 64, 66} <= set(r["rolls"])
        assert any("Fire damage halved" in n for n in r["notes"])

    def test_holder_cannot_be_burned(self):
        burned = Combatant("araquanid", spread=SPSpread(atk=32), alignment="Adamant",
                           ability="Water Bubble", item="Sitrus Berry", status="burn")
        r = calculate(burned, self.KING, "Liquidation", self.SINGLES)
        assert r["rolls"] == calculate(self.ARAQ_ATK, self.KING, "Liquidation", self.SINGLES)["rolls"]
        assert any("cannot be burned" in n for n in r["notes"])


class TestTerrainMechanics:
    """Terrain rules (Gen 8+ values). The expected rolls are the distinct one-hit
    damages the pokemon-showdown champions engine produced across 40 fixed
    seeds in singles (no crits); the surge ability sets the terrain on entry."""

    SINGLES = Field(is_doubles=False)
    KING = Combatant("kingambit", spread=SPSpread(hp=32), alignment="Adamant", ability="Defiant", item="Leftovers")
    CHOMP = Combatant("garchomp", spread=SPSpread(hp=32), alignment="Adamant", ability="Rough Skin", item="Leftovers")
    INDEEDEE = Combatant("indeedee-f", spread=SPSpread(spa=32), alignment="Modest", ability="Psychic Surge", item="Leftovers")
    PINCURCHIN = Combatant("pincurchin", spread=SPSpread(spa=32), alignment="Modest", ability="Electric Surge", item="Leftovers")
    # Wigglytuff: a Fairy with Galarian Weezing's 85 base SpA (the Weezing predictions did not make Regulation M-C).
    WIGGLYTUFF = Combatant("wigglytuff", spread=SPSpread(spa=32), alignment="Modest", ability="Cute Charm", item="Leftovers")
    RILLA = Combatant("rillaboom", spread=SPSpread(spa=32), alignment="Modest", ability="Grassy Surge", item="Leftovers")
    SNEASLER = Combatant("sneasler", spread=SPSpread(atk=32), alignment="Jolly", ability="Poison Touch")

    def test_expanding_force_is_x1_5_and_spread_on_psychic_terrain(self):
        r = calculate(self.INDEEDEE, self.CHOMP, "Expanding Force", Field(is_doubles=False, terrain="psychic"))
        assert r["rolls"] == [135, 138, 139, 141, 142, 144, 145, 147, 148, 150, 151, 153, 154, 156, 157, 160]
        dbl = calculate(self.INDEEDEE, self.CHOMP, "Expanding Force", Field(terrain="psychic"))
        assert max(dbl["rolls"]) == 120                      # x0.75: it became a spread move
        assert any("both opponents" in n for n in dbl["notes"])
        # an airborne user gets neither the boost nor the spread
        floating = Combatant("indeedee-f", spread=SPSpread(spa=32), alignment="Modest", ability="Levitate")
        assert calculate(floating, self.CHOMP, "Expanding Force", Field(terrain="psychic"))["rolls"] ==             calculate(floating, self.CHOMP, "Expanding Force", Field())["rolls"]

    def test_rising_voltage_doubles_into_grounded_targets_only(self):
        r = calculate(self.PINCURCHIN, self.KING, "Rising Voltage", Field(is_doubles=False, terrain="electric"))
        assert r["rolls"] == [153, 156, 157, 159, 160, 162, 165, 166, 168, 169, 171, 174, 175, 177, 178, 181]
        bird = Combatant("corviknight", spread=SPSpread(hp=32))
        on = calculate(self.PINCURCHIN, bird, "Rising Voltage", Field(is_doubles=False, terrain="electric"))["rolls"]
        off = calculate(self.PINCURCHIN, bird, "Rising Voltage", self.SINGLES)["rolls"]
        assert 1.25 < max(on) / max(off) < 1.35               # only the user's x1.3, no doubling
        grounded_bird = Combatant("corviknight", spread=SPSpread(hp=32), item="Iron Ball")
        ball = calculate(self.PINCURCHIN, grounded_bird, "Rising Voltage", Field(is_doubles=False, terrain="electric"))["rolls"]
        assert 2.5 < max(ball) / max(off) < 2.7               # Iron Ball grounds it: x1.3 x2

    def test_misty_explosion_and_terrain_pulse(self):
        r = calculate(self.WIGGLYTUFF, self.KING, "Misty Explosion", Field(is_doubles=False, terrain="misty"))
        assert r["rolls"] == [121, 123, 124, 126, 127, 129, 130, 132, 133, 135, 136, 138, 139, 141, 142, 144]
        tp = calculate(self.RILLA, self.KING, "Terrain Pulse", Field(is_doubles=False, terrain="grassy"))
        assert {43, 44, 45, 46, 47, 48, 49, 50, 51} <= set(tp["rolls"])
        assert tp["type"] == "Grass" and tp["base_power"] == 100
        plain = calculate(self.RILLA, self.KING, "Terrain Pulse", self.SINGLES)
        assert plain["type"] == "Normal" and plain["base_power"] == 50

    def test_psychic_terrain_blocks_priority_into_grounded_targets(self):
        ind = Combatant("indeedee-f", spread=SPSpread(hp=32), alignment="Calm", ability="Psychic Surge")
        for mv in ("Fake Out", "Sucker Punch", "Aqua Jet"):
            r = calculate(self.SNEASLER, ind, mv, Field(terrain="psychic"))
            assert max(r["rolls"]) == 0 and any("priority move blocked" in n for n in r["notes"]), mv
        assert max(calculate(self.SNEASLER, ind, "Close Combat", Field(terrain="psychic"))["rolls"]) > 0
        assert max(calculate(self.SNEASLER, ind, "Fake Out", Field())["rolls"]) > 0
        flying = Combatant("salamence-mega", ability="Aerilate")
        assert max(calculate(self.SNEASLER, flying, "Fake Out", Field(terrain="psychic"))["rolls"]) > 0

    def test_misty_halves_dragon_and_steel_roller_needs_terrain(self):
        chomp = Combatant("garchomp", spread=SPSpread(atk=32), alignment="Adamant", ability="Rough Skin")
        on = calculate(chomp, self.KING, "Dragon Claw", Field(terrain="misty"))["rolls"]
        off = calculate(chomp, self.KING, "Dragon Claw", Field())["rolls"]
        assert 0.45 < max(on) / max(off) < 0.55
        assert max(calculate(self.KING, self.CHOMP, "Steel Roller", Field())["rolls"]) == 0
        assert max(calculate(self.KING, self.CHOMP, "Steel Roller", Field(terrain="grassy"))["rolls"]) > 0
